config/routes.rb
Rails.application.routes.draw do
  # Home Page
  root 'static#home'

  # Signup
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  # Signout
  delete '/signout' => 'sessions#destroy'

  # Signin
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'

  # Google Auth
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  get '/categories/popular', to: 'categories#popular', as: 'popular'

  # Nested Route
  resources :categories, only: [:index, :new, :create] do
    resources :questions, only: [:index, :new, :create]
  end

  resources :users, only: [:index, :new, :create, :show]
    #resources :questions, only: [:edit, :destroy]
  


  resources :questions do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :questions, dependent: :destroy
    validates :name, presence: :true 
    validates_uniqueness_of :name, message: "that category has already been created."

    def self.most_popular
        self.all.sort_by{|c|c.questions.count}.reverse[0..2]
        #sort by question count
      end
    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question

  accepts_nested_attributes_for :user

  validates :content, presence: :true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :comments
  has_many :users, through: :comments

  accepts_nested_attributes_for :user, :category

  validates_presence_of :title
  validates_presence_of :category
  validates_presence_of :content
  validates_uniqueness_of :content
end

app/models/user.rb
class User < ApplicationRecord
    has_many :questions, dependent: :destroy
    has_many :categories, through: :questions
    has_many :comments
    has_many :commented_posts, through: :comments, source: :question

    has_secure_password

    validates :email, uniqueness: true 
    validates :username, :email, presence: true 

    scope :ordered_by_username, -> {order(username: :asc)}

    
    def self.create_from_omniauth(auth)
        User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            u.username = auth['info']['first_name']
            u.email = auth['info']['email']
            u.password = SecureRandom.hex(16)
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  rescue_from ActiveRecord::RecordNotFound, with: :handle_record_not_found
  protect_from_forgery with: :exception
  
  private

  def handle_record_not_found
    render :"shared/not_found"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :redirect_if_not_signed_in, only: [:new, :create]
    
    def index
        @categories = Category.all
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            redirect_to categories_path
        else
            render :new
        end
    end

    def popular
        @categories = Category.most_popular
     end

private

    def category_params
        params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :redirect_if_not_signed_in

    def new
        if params[:question_id] && @question = Question.find_by_id(params[:question_id])
            @comment = @question.comments.build
        else
            redirect_to questions_path
        end
    end

    def create
        @question = Question.find_by_id(params[:question_id])
        @comment = current_user.comments.build(comment_params)
        if @comment.save
            redirect_to question_path(@comment.question)
        else
            render :new
        end
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:content, :question_id, :user_id)
    end
  end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :find_question, only: [:edit, :update, :show, :destroy]
    before_action :redirect_if_not_signed_in, only: [:new, :create, :edit, :update, :destroy]
    before_action :redirect_if_not_authorized, only: [:edit, :update, :destroy]

    def index
        if params[:category_id] && @category = Category.find_by_id(params[:category_id])
            @questions = @category.questions
        else
            @questions = Question.all
        end
    end

    def new
        if params[:category_id] && @category = Category.find_by_id(params[:category_id])
            @question = @category.questions.build
        else
            @question = Question.new  
            @question.build_category
        end
    end

    def create
        @question = current_user.questions.build(question_params)
        if @question.valid?
            @question.save
            redirect_to question_path(@question)
        else
            @category = Category.find_by_id(params[:category_id]) if params[:category_id]
            render "new"
        end
    end

    def show
    end

    def edit 
    end

    def update 
        if @question.valid?
            @question.update(question_params)
            redirect_to question_path(@question)
        else 
            render :edit 
        end
    end

    def destroy
        @question.destroy
        redirect_to user_path(current_user)
    end
    
private

    def question_params
        params.require(:question).permit(:title, :content, :category_id)
    end

    def find_question
        @question = Question.find(params[:id])
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def omniauth  #log users in with omniauth
        user = User.create_from_omniauth(auth)
        if user.save!   #valid?
            session[:user_id] = user.id
            redirect_to user
        else
            flash[:message] = user.errors.full_messages.join(", ")
            redirect_to root_path, alert: "Invalid username or password. Please try again."
        end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            flash[:message] = "Invalid username or password. Please try again" 
            redirect_to signin_path
        end
    end

    def destroy
        session.clear
        redirect_to root_path
    end

private
    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def home
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all.ordered_by_username
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        @questions = @user.questions
    end

private

    def user_params
        params.require(:user).permit(:email, :username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end
    
    def signed_in?
        !!session[:user_id]
    end

    def redirect_if_not_signed_in
        flash[:error] = "Please Sign in."
        redirect_to signin_path if !signed_in?
    end

    def authorized?
        @question.user == current_user
    end

    def redirect_if_not_authorized
        flash[:error] = "You can only edit your own question."
        redirect_to questions_path if !authorized?
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

    def questions_header
        if @category
            tag.h1("Questions about #{@category.name.capitalize}")
        else
            tag.h1("All Questions")
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<h1>All Categories</h1>

<h3><%= link_to "Add new Category", new_category_path %></h3>

<h4><%= link_to "What's the most popular category?", popular_path %></h4>


<% @categories.each do |f| %>
    <li><%= link_to f.name, category_questions_path(f) %></li>
    <li><%= link_to "Add new question", new_category_question_path(f) %></li>
    <br>
    ____________________________________
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render partial: "shared/errors", locals: {object: @category} %>

<%= form_for @category do |f| %>
    <%= f.label :name %>:
    <%= f.text_field :name %>
    <br>
    <%= f.submit %>
<% end %>

app/views/categories/popular.html.erb
<h1>Top Three Categories!!!</h1>



<br>


    <% @categories.each do |c| %>
       <%= link_to c.name, categories_path(c) %>
        <br>
    
    <% end %>

app/views/comments/new.html.erb
<h1>New Comment</h2>

<%= render partial: "shared/errors", locals: {object: @comment} %>

<%= form_for ([@question,@comment]) do |f| %>
    <%= f.hidden_field :question_id %>
    <%= f.label :content, "New Comment" %>:
    <br>
    <%= f.text_area :content %>
    <br>
    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Ask a Parent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <b4-body>
  <header role="banner">
  <%= link_to image_tag('logo.PNG', alt: 'logo'), root_path %><br>

    <nav id="navbar-primary" class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
    </div>
    <div class="collapse navbar-collapse" id="navbar-primary-collapse">
      <ul class="nav navbar-nav">
        <% if signed_in? %>

          <%= link_to image_tag("profile.PNG"), user_path(current_user) %>
          <%= link_to image_tag("newquestion.PNG"), new_question_path %>
          <%= link_to image_tag("allquestions.PNG"), questions_path %>
          <%= link_to image_tag("categories.PNG"), categories_path %>
          <%= link_to image_tag("users.PNG"), users_path %>
          <%= link_to image_tag("signout.PNG"), signout_path, method: "delete" %>
<hr>

        <% else %><hr>
          <li class="active"><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Sign In", signin_path %></li><hr>
          <li><%= link_to "Categories", categories_path %></li>
          <li><%= link_to "Newest Questions", questions_path %></li>
          <li><%= link_to "All Users", users_path %></li><hr>
         
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header><!-- header role="banner" -->
  <body>
    
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= render partial: "shared/errors", locals: {object: @question} %>

<%= form_for([@category, @question]) do |f| %>
    <%= f.label :title, "question:" %>
    <%= f.text_field :title%>
    <br>
    <%= f.label :content, "Details:" %>
    <%= f.text_area :content %>
    <br>
    <%= f.label :category, "Category:" %>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
    <br>
    <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Questions</h1>
<br>
<%= render 'form' %>

app/views/questions/index.html.erb
<%= questions_header %>

<% @questions.reverse.each do |p| %>
    Title: <%= link_to p.title, question_path(p) %>
    <br>
    <br>
    Asked By: <%= link_to p.user.username, user_path(p.user) %></li>
    <br>
    _____________________________________________
    <br>
    <br>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>
<br>
<%= render 'form'%>

app/views/questions/show.html.erb
<%= render partial: "shared/errors", locals: {object: @question} %>
<hr>
<p>Author: <%= link_to @question.user.username, user_path(@question.user) %>
Category: <%= link_to @question.category.name, category_questions_path(@question.category) %></p>

<h1>Title: <%= @question.title %></h1>
<h4> <%= @question.content %> </h4>


<br>

<% if authorized? %> 
  <%= link_to "Edit question", edit_question_path(@question)%> | 
  <%= link_to "Delete question", question_path(@question.id), method: 'delete'%>
<% end %>
<hr>
<br>
<br>
<%= link_to "Add New Comment", new_question_comment_path(@question) %>



      <% @question.comments.reverse.each do |c| %>
      <div class="ui comments">
        <h3 class="ui dividing header">Comment</h3>
        <div class="comment">
          <div class="content">
            <a class="author"> Username: <%= link_to c.user.username, user_path(c) %>  </a>
            <br>
            <div class="text">
              Comment: <%= c.content %>
            </div>
          
          </div>
        </div>
      
      <% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %> 

app/views/shared/not_found.html.erb
<h1><%= "Sorry, I can't find that record. Double check the URL and try again!" %></h1>

app/views/users/index.html.erb
<h1>Users:</h2>

<ul>
<% @users.each do |f| %>
    <li>
        <%= link_to f.username, user_path(f) %>
    </li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<br>

<%= render partial: "shared/errors", locals: {object: @user} %>

<%= form_for @user do |f| %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <br>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <br>
    <%= f.submit "Submit" %>
<% end %>

<br>
<p>Or</p>
<br>
<%= button_to "Sign in with Google", '/auth/google_oauth2' %>

app/views/users/show.html.erb
<h1><%= @user.username.capitalize %>'s Profile:</h1>
<br>
<br>
<h2>questions:</h2>
<% @questions.each do |f| %>
    <li><%= link_to f.title, question_path(f)%></li>
    <br>
<% end %>
<br>

<h3>Comments:</h3>

<% @user.comments.each do |f| %>
    <li><%= link_to f.content, question_path(f.question_id) %></li>
    <br>
<% end %>